apiVersion: v1
kind: Pod
metadata:
  name: config-env-pod
  labels:
    app: config-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
  restartPolicy: Never
