apiVersion: v1
kind: Pod
metadata:
  name: config-vol-pod
  labels:
    app: config-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  restartPolicy: Never
