apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  labels:
    app: secret-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: DB_USER
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: DB_PASS
  restartPolicy: Never
